/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projeto1;

/**
 *
 * @author Asus
 */
public class AppCorrida extends javax.swing.JFrame {

    /**
     * Creates new form AppCorrida
     */
    public AppCorrida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAdicionarCarro = new javax.swing.JDialog();
        jPanelPainelAdicionarCarro = new javax.swing.JPanel();
        jPanelEcra = new javax.swing.JPanel();
        jLabelTempo = new javax.swing.JLabel();
        jLabelVelocidade = new javax.swing.JLabel();
        jLabelCombustivel = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldPlaca = new javax.swing.JTextField();
        jButtonAdicionar = new javax.swing.JButton();
        jSpinnerCombustivel = new javax.swing.JSpinner();
        jSpinnerVelocidade = new javax.swing.JSpinner();
        jSpinnerTempo = new javax.swing.JSpinner();
        jDialogVerListaCondutorCarro = new javax.swing.JDialog();
        jPanelPainel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDialogPartida = new javax.swing.JDialog();
        jPanelPainel3 = new javax.swing.JPanel();
        jPanelPartidas = new javax.swing.JPanel();
        jPanelVencedor = new javax.swing.JPanel();
        jLabelVencedor = new javax.swing.JLabel();
        jTextFieldVencedor = new javax.swing.JTextField();
        jPanelTempo = new javax.swing.JPanel();
        jLabelTempoVencedor = new javax.swing.JLabel();
        jTextFieldTempoChegada = new javax.swing.JTextField();
        jButtonPartir = new javax.swing.JButton();
        jDialogAdicionarCondutor = new javax.swing.JDialog();
        jPanelPainel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelIdade = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jSpinnerIdade = new javax.swing.JSpinner();
        jButtonAdicionarCondutor = new javax.swing.JButton();
        jPanelPainel = new javax.swing.JPanel();
        jLabelFoto = new javax.swing.JLabel();
        jMenuBarListaMenu = new javax.swing.JMenuBar();
        jMenuAplicacao = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuCentroCorridas = new javax.swing.JMenu();
        jMenuItemAdicionar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItemVer = new javax.swing.JMenuItem();
        jMenuItemPartidas = new javax.swing.JMenuItem();

        jDialogAdicionarCarro.setTitle("Adicionar Carro");
        jDialogAdicionarCarro.setMinimumSize(new java.awt.Dimension(700, 500));

        jPanelPainelAdicionarCarro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelEcra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicione uma viatura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabelTempo.setText("Tempo:");

        jLabelVelocidade.setText("Velocidade:");

        jLabelCombustivel.setText("Combustivel:");

        jLabelPlaca.setText("Placa:");

        jLabelModelo.setText("Modelo:");

        jLabelMarca.setText("Marca:");

        jButtonAdicionar.setText("Adicionar");

        javax.swing.GroupLayout jPanelEcraLayout = new javax.swing.GroupLayout(jPanelEcra);
        jPanelEcra.setLayout(jPanelEcraLayout);
        jPanelEcraLayout.setHorizontalGroup(
            jPanelEcraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEcraLayout.createSequentialGroup()
                .addGroup(jPanelEcraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAdicionar)
                    .addGroup(jPanelEcraLayout.createSequentialGroup()
                        .addGroup(jPanelEcraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelTempo)
                            .addComponent(jLabelVelocidade)
                            .addGroup(jPanelEcraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelEcraLayout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanelEcraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelModelo)
                                        .addComponent(jLabelMarca)
                                        .addComponent(jLabelPlaca)))
                                .addGroup(jPanelEcraLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabelCombustivel))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelEcraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelEcraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSpinnerTempo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addComponent(jSpinnerVelocidade, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanelEcraLayout.setVerticalGroup(
            jPanelEcraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEcraLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelEcraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMarca)
                    .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEcraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelModelo)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEcraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPlaca)
                    .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEcraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCombustivel)
                    .addComponent(jSpinnerCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEcraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVelocidade)
                    .addComponent(jSpinnerVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEcraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTempo)
                    .addComponent(jSpinnerTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButtonAdicionar))
        );

        javax.swing.GroupLayout jPanelPainelAdicionarCarroLayout = new javax.swing.GroupLayout(jPanelPainelAdicionarCarro);
        jPanelPainelAdicionarCarro.setLayout(jPanelPainelAdicionarCarroLayout);
        jPanelPainelAdicionarCarroLayout.setHorizontalGroup(
            jPanelPainelAdicionarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPainelAdicionarCarroLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanelEcra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelPainelAdicionarCarroLayout.setVerticalGroup(
            jPanelPainelAdicionarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPainelAdicionarCarroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanelEcra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogAdicionarCarroLayout = new javax.swing.GroupLayout(jDialogAdicionarCarro.getContentPane());
        jDialogAdicionarCarro.getContentPane().setLayout(jDialogAdicionarCarroLayout);
        jDialogAdicionarCarroLayout.setHorizontalGroup(
            jDialogAdicionarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAdicionarCarroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPainelAdicionarCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialogAdicionarCarroLayout.setVerticalGroup(
            jDialogAdicionarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAdicionarCarroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPainelAdicionarCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialogVerListaCondutorCarro.setTitle("Ver Lista");
        jDialogVerListaCondutorCarro.setMinimumSize(new java.awt.Dimension(600, 700));

        jPanelPainel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Veja a Lista", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carros", "Condutores"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelPainel2Layout = new javax.swing.GroupLayout(jPanelPainel2);
        jPanelPainel2.setLayout(jPanelPainel2Layout);
        jPanelPainel2Layout.setHorizontalGroup(
            jPanelPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPainel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(441, Short.MAX_VALUE))
        );
        jPanelPainel2Layout.setVerticalGroup(
            jPanelPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPainel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogVerListaCondutorCarroLayout = new javax.swing.GroupLayout(jDialogVerListaCondutorCarro.getContentPane());
        jDialogVerListaCondutorCarro.getContentPane().setLayout(jDialogVerListaCondutorCarroLayout);
        jDialogVerListaCondutorCarroLayout.setHorizontalGroup(
            jDialogVerListaCondutorCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVerListaCondutorCarroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanelPainel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialogVerListaCondutorCarroLayout.setVerticalGroup(
            jDialogVerListaCondutorCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogVerListaCondutorCarroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPainel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialogPartida.setTitle("Partidas");
        jDialogPartida.setMinimumSize(new java.awt.Dimension(700, 400));

        jPanelPainel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanelPartidas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Partidas dos Carros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        jPanelVencedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelVencedor.setText("VENCEDOR:");

        javax.swing.GroupLayout jPanelVencedorLayout = new javax.swing.GroupLayout(jPanelVencedor);
        jPanelVencedor.setLayout(jPanelVencedorLayout);
        jPanelVencedorLayout.setHorizontalGroup(
            jPanelVencedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVencedorLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabelVencedor)
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(jPanelVencedorLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jTextFieldVencedor)
                .addContainerGap())
        );
        jPanelVencedorLayout.setVerticalGroup(
            jPanelVencedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVencedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVencedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldVencedor, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelTempo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelTempoVencedor.setText("TEMPO:");

        javax.swing.GroupLayout jPanelTempoLayout = new javax.swing.GroupLayout(jPanelTempo);
        jPanelTempo.setLayout(jPanelTempoLayout);
        jPanelTempoLayout.setHorizontalGroup(
            jPanelTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTempoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabelTempoVencedor)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(jPanelTempoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldTempoChegada)
                .addContainerGap())
        );
        jPanelTempoLayout.setVerticalGroup(
            jPanelTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTempoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTempoVencedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTempoChegada, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonPartir.setText("Partir");

        javax.swing.GroupLayout jPanelPartidasLayout = new javax.swing.GroupLayout(jPanelPartidas);
        jPanelPartidas.setLayout(jPanelPartidasLayout);
        jPanelPartidasLayout.setHorizontalGroup(
            jPanelPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPartidasLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPartidasLayout.createSequentialGroup()
                        .addComponent(jButtonPartir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelVencedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanelPartidasLayout.setVerticalGroup(
            jPanelPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPartidasLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanelVencedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanelPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPartidasLayout.createSequentialGroup()
                        .addComponent(jPanelTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPartidasLayout.createSequentialGroup()
                        .addComponent(jButtonPartir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );

        javax.swing.GroupLayout jPanelPainel3Layout = new javax.swing.GroupLayout(jPanelPainel3);
        jPanelPainel3.setLayout(jPanelPainel3Layout);
        jPanelPainel3Layout.setHorizontalGroup(
            jPanelPainel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPainel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelPartidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelPainel3Layout.setVerticalGroup(
            jPanelPainel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPainel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPartidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialogPartidaLayout = new javax.swing.GroupLayout(jDialogPartida.getContentPane());
        jDialogPartida.getContentPane().setLayout(jDialogPartidaLayout);
        jDialogPartidaLayout.setHorizontalGroup(
            jDialogPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPartidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPainel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialogPartidaLayout.setVerticalGroup(
            jDialogPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPartidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPainel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialogAdicionarCondutor.setMinimumSize(new java.awt.Dimension(500, 300));

        jPanelPainel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adicionar Condutor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 255))); // NOI18N

        jLabelNome.setText("Nome:");

        jLabelIdade.setText("Idade:");

        jSpinnerIdade.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        jButtonAdicionarCondutor.setText("Adicionar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAdicionarCondutor)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabelIdade)
                            .addGap(18, 18, 18)
                            .addComponent(jSpinnerIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabelNome)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdade)
                    .addComponent(jSpinnerIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButtonAdicionarCondutor))
        );

        javax.swing.GroupLayout jPanelPainel4Layout = new javax.swing.GroupLayout(jPanelPainel4);
        jPanelPainel4.setLayout(jPanelPainel4Layout);
        jPanelPainel4Layout.setHorizontalGroup(
            jPanelPainel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPainel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelPainel4Layout.setVerticalGroup(
            jPanelPainel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPainel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogAdicionarCondutorLayout = new javax.swing.GroupLayout(jDialogAdicionarCondutor.getContentPane());
        jDialogAdicionarCondutor.getContentPane().setLayout(jDialogAdicionarCondutorLayout);
        jDialogAdicionarCondutorLayout.setHorizontalGroup(
            jDialogAdicionarCondutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAdicionarCondutorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPainel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialogAdicionarCondutorLayout.setVerticalGroup(
            jDialogAdicionarCondutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAdicionarCondutorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelPainel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App Corridas");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanelPainel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPainel.setForeground(new java.awt.Color(51, 255, 51));

        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Carros.jpg"))); // NOI18N
        jLabelFoto.setText("jLabel1");

        javax.swing.GroupLayout jPanelPainelLayout = new javax.swing.GroupLayout(jPanelPainel);
        jPanelPainel.setLayout(jPanelPainelLayout);
        jPanelPainelLayout.setHorizontalGroup(
            jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPainelLayout.setVerticalGroup(
            jPanelPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPainelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jMenuAplicacao.setText("Aplicação");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAplicacao.add(jMenuItem1);

        jMenuBarListaMenu.add(jMenuAplicacao);

        jMenuCentroCorridas.setText("Centro de Corridas");

        jMenuItemAdicionar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAdicionar.setText("Adicionar Carro");
        jMenuItemAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdicionarActionPerformed(evt);
            }
        });
        jMenuCentroCorridas.add(jMenuItemAdicionar);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Adicionar Condutor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuCentroCorridas.add(jMenuItem2);

        jMenuItemVer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVer.setText("Ver Lista de Carros");
        jMenuItemVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerActionPerformed(evt);
            }
        });
        jMenuCentroCorridas.add(jMenuItemVer);

        jMenuItemPartidas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemPartidas.setText("Partidas");
        jMenuItemPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPartidasActionPerformed(evt);
            }
        });
        jMenuCentroCorridas.add(jMenuItemPartidas);

        jMenuBarListaMenu.add(jMenuCentroCorridas);

        setJMenuBar(jMenuBarListaMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
          this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdicionarActionPerformed
       jDialogAdicionarCarro.setVisible(true);
    }//GEN-LAST:event_jMenuItemAdicionarActionPerformed

    private void jMenuItemVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerActionPerformed
       jDialogVerListaCondutorCarro.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerActionPerformed

    private void jMenuItemPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPartidasActionPerformed
       jDialogPartida.setVisible(true);
    }//GEN-LAST:event_jMenuItemPartidasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       jDialogAdicionarCondutor.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppCorrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppCorrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppCorrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppCorrida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppCorrida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonAdicionarCondutor;
    private javax.swing.JButton jButtonPartir;
    private javax.swing.JDialog jDialogAdicionarCarro;
    private javax.swing.JDialog jDialogAdicionarCondutor;
    private javax.swing.JDialog jDialogPartida;
    private javax.swing.JDialog jDialogVerListaCondutorCarro;
    private javax.swing.JLabel jLabelCombustivel;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelTempo;
    private javax.swing.JLabel jLabelTempoVencedor;
    private javax.swing.JLabel jLabelVelocidade;
    private javax.swing.JLabel jLabelVencedor;
    private javax.swing.JMenu jMenuAplicacao;
    private javax.swing.JMenuBar jMenuBarListaMenu;
    private javax.swing.JMenu jMenuCentroCorridas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAdicionar;
    private javax.swing.JMenuItem jMenuItemPartidas;
    private javax.swing.JMenuItem jMenuItemVer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelEcra;
    private javax.swing.JPanel jPanelPainel;
    private javax.swing.JPanel jPanelPainel2;
    private javax.swing.JPanel jPanelPainel3;
    private javax.swing.JPanel jPanelPainel4;
    private javax.swing.JPanel jPanelPainelAdicionarCarro;
    private javax.swing.JPanel jPanelPartidas;
    private javax.swing.JPanel jPanelTempo;
    private javax.swing.JPanel jPanelVencedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerCombustivel;
    private javax.swing.JSpinner jSpinnerIdade;
    private javax.swing.JSpinner jSpinnerTempo;
    private javax.swing.JSpinner jSpinnerVelocidade;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPlaca;
    private javax.swing.JTextField jTextFieldTempoChegada;
    private javax.swing.JTextField jTextFieldVencedor;
    // End of variables declaration//GEN-END:variables
}
